image: ubuntu:22.04

workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - apt-get update
    - apt-get -y install wget
    - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.39.0/install.sh | bash
    - source ~/.bashrc
    - source ~/.profile
    - source ~/.nvm/nvm.sh
    - nvm install v18.15.0
    - nvm use v18.15.0
    - npm install
    - npm run build-storybook -- -o storybook-static
    - cp -a storybook-static/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
