# .github/workflows/deploy-github-pages.yaml

# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - main # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - name: Checkout respository
        uses: actions/checkout@v4

      # Set up Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Cache Node.js modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Update dependencies
        run: npm update

      - name: Clean installation
        run: npm ci --force

      - name: Verify @mdi/font installation
        run: npm ls @mdi/font

      - name: Build Storybook
        run: npx storybook build --output-dir /storybook-static/

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - name: Deploy to Github Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/storybook-static
          clean: true
